name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "bash -c 'echo \"SELECT 1\" | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd'"
          --health-interval 10s --health-timeout 30s --health-retries 20 --health-start-period 30s
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Wait for MSSQL
        run: |
          for i in {1..30}; do
            nc -z localhost 1433 && echo "MSSQL is up" && break
            echo "Waiting for MSSQL..."
            sleep 10
          done
      - name: Run tests
        run: |
          cargo test
          cargo test -- --ignored
