name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "bash -c 'echo \"SELECT 1\" | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd'" \
          --health-interval 10s --health-timeout 30s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run tests
        run: |
          cargo test
          cargo test -- --ignored
